### ISSUE TITLE
1.7-pre1: Resource loader stuck in loop due to rendererMixin.

### ISSUE THREAD

**Issue by lospejos** [StellarWind22/Fabric-Shield-Lib#127] opened 2022-12-23 16:58 UTC
Mods installed:

`fabric-api-0.69.1+1.19.3`
`modmenu-5.0.2`
`FabricShieldLib-1.7.0-pre1-1.19`

When started, MC is eternally loops.
No crashdump generated.
Logs attached here: 
[latest.log](https://github.com/CrimsonDawn45/Fabric-Shield-Lib/files/10296299/latest.log)

Video of this loop is here: 

https://user-images.githubusercontent.com/4608475/209373040-3787fc20-0e0f-4168-a3a0-109a32aa4c43.mp4

If I remove `FabricShieldLib-1.7.0-pre1-1.19` mod, Minecraft loads successfully.

Please assist. Thanks.

**Comment by CringeStar** [comment] 2022-12-23 17:11
This is an issue we've encountered before, but I am not sure of the cause this time around.
I found this in the log:
```
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class de.guntram.mcmod.crowdintranslate.CTResourcePack does not define or inherit an implementation of the resolved method 'abstract void method_14408(net.minecraft.class_3264, java.lang.String, java.lang.String, net.minecraft.class_3262$class_7664)' of interface net.minecraft.class_3262.
```

**Comment by CrimsonDawn45** [comment] 2022-12-23 18:01
> This is an issue we've encountered before, but I am not sure of the cause this time around. I found this in the log:
> 
> ```
> Caught error loading resourcepacks, removing all selected resourcepacks
> java.util.concurrent.CompletionException: java.lang.AbstractMethodError: Receiver class de.guntram.mcmod.crowdintranslate.CTResourcePack does not define or inherit an implementation of the resolved method 'abstract void method_14408(net.minecraft.class_3264, java.lang.String, java.lang.String, net.minecraft.class_3262$class_7664)' of interface net.minecraft.class_3262.
> ```

Yeah we have definitely had this problem before... I can't remember exactly how we fixed it but I know it has to do with the render mixin that we use to register the texture for the banner shield models

**Comment by CrimsonDawn45** [comment] 2022-12-23 18:05
```java
public interface ShieldSetModelCallback {

    /**
     * Handle event listeners
     */
    Event<ShieldSetModelCallback> EVENT = EventFactory.createArrayBacked(ShieldSetModelCallback.class, 
            (listeners) -> (loader) -> {
                for (ShieldSetModelCallback listener : listeners) {
                    ActionResult result = listener.setModel(loader);

                    if (result != ActionResult.PASS) {
                        return result;
                    }
                }

                return ActionResult.PASS;
            });

    ActionResult setModel(EntityModelLoader loader);
}
```
It has something to do with how this loops & it's like not terminating correctly which is causing the bootloop

**Comment by CrimsonDawn45** [comment] 2022-12-23 23:13
I think If we look more into how regular entity models have their texture registered & create our own duplicate of the `ShieldEntityModel` & change it around to act as a template like the `FabricShieldBannerItem` class we might be able to just remove the renderer mixin & use the regular method for registering the texture?

**Comment by CringeStar** [comment] 2023-03-04 18:13
@lospejos does this still occur? On my end, in a dev environment, I cannot replicate this

**Comment by CringeStar** [comment] 2023-03-04 18:24
nvm, i replicated it, it only happens outside of the dev environment

**Comment by CringeStar** [comment] 2023-03-04 19:09
this was simply a problem with crowdlin translate, so I will remove it from the mod and release a new version

**Closed** 2023-03-05 05:35 UTC
Labels: bug, client, needs investigation, 1.19
